scalar UUID
scalar BigDecimal
scalar LocalTime

enum STATUS {
    ACTIVE
    CHECKED_OUT
    ABANDONED
}

type Cart {
    cartId: UUID!
    userId: UUID!
    restaurantId: UUID!
    status: STATUS!
    createdAt: LocalTime
    updatedAt: LocalTime
    cartItems: [CartItem!]!
}

type CartItem {
    cartItemId: UUID!
    menuItemId: UUID!
    itemName: String!
    unitPrice: BigDecimal!
    quantity: Int!
    totalPrice: BigDecimal!
    createdAt: LocalTime
    updatedAt: LocalTime
    cart: Cart
}

type Query {
    cartByUserId(userId: UUID!): Cart
    cartItemsByCartId(cartId: UUID!): [CartItem!]!
}