spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/authdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:your_password}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    topics:
      user: user-topic
      notification: notification-topic

server:
  port: ${APPLICATION_PORT:8090}
  servlet:
    context-path: /api

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET}
  AccessTokenExpiration: 900000
  refreshTokenExpiration: 604800000