spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL:jdbc:h2:mem:authdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    topics:
      user: user-topic
      notification: notification-topic

server:
  port: ${APPLICATION_PORT}
  servlet:
    context-path: /api

logging:
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSL}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
  level:
    root: INFO
    com:
      ps:
        backend: DEBUG
  file:
    name: ../logs/${spring.application.name}.log
jwt:
  secret: ${JWT_SECRET}
  AccessTokenExpiration: 900000
  refreshTokenExpiration: 604800000

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    description: Auth Service
    version: 1.0.0
